# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89382ffca07224842c711be42579660815ba5f8daf0ba8401bfdf18b066bd2d1397b565110117b344c7e8272dd80c0288527182d487c2dda9b638bd45de2fa49

test:
  secret_key_base: e174710db0d07d1f4b35b77d2401182cbeafd8b94222bd43fe2d61f4da12fa4864ba0b5ba1fe5075ee7b9a25bbee482b4705bbbadb1dfd8e13f59a2ff6aab5dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
